### ISSUE TITLE
Duplicative header

### ISSUE THREAD

**Issue by davidbernick** [broadinstitute/dsp-appsec-infrastructure-apps#487]
https://github.com/broadinstitute/dsp-appsec-infrastructure-apps/blob/08d51210ad6017cebb68775ac41aaa5291f9972a/sdarq/frontend/src/app/security-controls/security-controls.component.html#L21

Both of these say "list security controls" -- while the description tells us what each does, the headline on both is the same. They should be different. And frankly I do think that we don't need the "search for my service" as a separate box here. I think if we just had an auto-complete search bar on this page that went right to your service, that'd be best. But having two boxes with 2 different functions that are both called "list security controls" is confusing.

**Comment by zbedo** [comment]
Hi, thanks for reporting this. Just created a PR to address this issue.
